=== reggensc/poschtiapp/poschtiapp/poschtiapp-persistence/src/test/resources/dbunit/dataset.dtd
<?xml version="1.0" encoding="UTF-8"?>

<!ELEMENT dataset (
        revinfo+,
        aud_map_owners+,
        aud_ref_state+,
        aud_ref_unit+,
        aud_shoppinglist_shoppingcategory+,
        aud_tbl_shoppingcategory+,
        aud_tbl_shoppingitem+,
        aud_tbl_shoppinglist+,
        aud_tbl_user+,
        ref_unit+,
        ref_state+,
        tbl_user+,
        tbl_shoppinglist+,
        map_owners+,
        tbl_shoppingcategory+,
        tbl_shoppingitem+
    )
>

<!ELEMENT revinfo EMPTY>
<!ELEMENT aud_map_owners EMPTY>
<!ELEMENT aud_ref_state EMPTY>
<!ELEMENT aud_ref_unit EMPTY>
<!ELEMENT aud_shoppinglist_shoppingcategory EMPTY>
<!ELEMENT aud_tbl_shoppingcategory EMPTY>
<!ELEMENT aud_tbl_shoppingitem EMPTY>
<!ELEMENT aud_tbl_shoppinglist EMPTY>
<!ELEMENT aud_tbl_user EMPTY>

<!ELEMENT ref_unit EMPTY>
<!ATTLIST ref_unit 
    id CDATA #REQUIRED
    designator CDATA #REQUIRED
>

<!ELEMENT ref_state EMPTY>
<!ATTLIST ref_state 
    id CDATA #REQUIRED
    designator CDATA #REQUIRED
>

<!ELEMENT tbl_user EMPTY>
<!ATTLIST tbl_user
    id CDATA #REQUIRED
    email  CDATA #REQUIRED
    firstName CDATA #IMPLIED
    lastName  CDATA #IMPLIED  
>

<!ELEMENT tbl_shoppinglist EMPTY>
<!ATTLIST tbl_shoppinglist
    id CDATA #REQUIRED
    name CDATA #REQUIRED
    state_id CDATA #REQUIRED
>

<!ELEMENT map_owners EMPTY>
<!ATTLIST map_owners
    list_id CDATA #REQUIRED
    user_id CDATA #REQUIRED
>

<!ELEMENT tbl_shoppingcategory EMPTY>
<!ATTLIST tbl_shoppingcategory
    id CDATA #REQUIRED
    name CDATA #REQUIRED 
    list_id  CDATA #IMPLIED
    list_index  CDATA #IMPLIED 
>

<!ELEMENT tbl_shoppingitem EMPTY>
<!ATTLIST tbl_shoppingitem
    id CDATA #REQUIRED
    name CDATA #REQUIRED
    description CDATA #IMPLIED
    quantity CDATA #IMPLIED 
    unit_id CDATA #IMPLIED
    category_id CDATA #IMPLIED 
    category_index CDATA #IMPLIED
>

=== reggensc/poschtiapp/poschtiapp/poschtiapp-persistence/src/test/resources/dbunit/reference_db.dbunit.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE dataset SYSTEM "dataset.dtd">

<dataset>
	<revinfo />
	<aud_map_owners />
	<aud_ref_state />
	<aud_ref_unit />
	<aud_shoppinglist_shoppingcategory />
	<aud_tbl_shoppingcategory />
	<aud_tbl_shoppingitem />
	<aud_tbl_shoppinglist />
	<aud_tbl_user />

	<ref_unit id="1" designator="qty" />
	<ref_unit id="2" designator="liter" />

	<ref_state id="1" designator="TestState" />
	<ref_state id="2" designator="Created" />
	<ref_state id="3" designator="Purchased" />

	<tbl_user id="1" email="test.email@testdata.org" firstName="TestFirstName" lastName="TestLastName" password="1234" />
	<tbl_user id="2" email="hans.muster@testdata.org" firstName="Hans" lastName="Muster" password="1234" />
	<tbl_user id="3" email="rene.eggenschwiler@testdata.org" firstName="Hans" lastName="Muster" password="1234" />

	<tbl_shoppinglist id="1" name="Test ShoppingList 1" state_id="2" />
	<tbl_shoppinglist id="2" name="Test ShoppingList 2" state_id="2" />
	<tbl_shoppinglist id="3" name="Test ShoppingList 3" state_id="2" />

	<map_owners list_id="1" user_id="2" />
	<map_owners list_id="2" user_id="2" />
	<map_owners list_id="3" user_id="2" />

	<tbl_shoppingcategory id="1" name="Test Category 1" />
	<tbl_shoppingcategory id="2" name="Test Category i0" list_id="3" list_index="0" />
	<tbl_shoppingcategory id="3" name="Test Category i1" list_id="3" list_index="1" />
	<tbl_shoppingcategory id="4" name="Test Category 4" />

	<tbl_shoppingitem id="1" name="Test Item" description="Test Description" quantity="3" unit_id="2"
		category_id="4" category_index="0" />

</dataset>
